export let geo_data = require("../assests/final_data.json") //data_corrected for v1 and data for v0

export const node_and_neighbours = require("../assests/neighbours.json")

export const saved_paths = require("../assests/paths.json")


const locations_arr_calc = (arr) => {
    const output = []
    arr.forEach(node => {
        output.push({
            'id': node.id,
            'pos': [node.lat, node.lon]
        })
    });
    return output
}

export const updateLatLon = (arr, id, pos) => {
    let node = arr.find(e => e.id === id)
    node.lat = pos.lat
    node.lon = pos.lon
}


export const locations_arr = locations_arr_calc(geo_data)


export const get_label_id = (label) => {
    const entry = labels_detail.find(e => e.label === label)
    return entry.id
}

export const LABELS =
    ['KU Football Ground',
        'KU Boys Hostel',
        'KU Corner',
        'KU Library',
        'aqua',
        'Cricket Pitch',
        'Department of Mathematics',
        'Block No 10',
        'KU Chinese Hall',
        'SHEDS',
        'Department of Environmental Science and Engineering',
        'Administration Block',
        'KU Girls Hostel New',
        'Electronics and Electrical Engineering Block',
        'Department of Civil Engineering',
        'KU Mesh',
        'Block: 06',
        'KU Park',
        'Main Building',
        'CV Raman Auditorium',
        'Department of Biotechnology',
        'KU Bike Parking',
        'KU Fountain',
        'Engineering Drawing Lab',
        'Department of Architecture',
        'High Voltage Lab',
        'Girls Hostel',
        'KU Automobile Lab',
        'Dean Office SoS',
        'Electronics and Electrical Lab',
        'Multipurpose Hall',
        'WEIR',
        'Library Lawn',
        'KU Technical Training Center',
        'Nepal Technology Innovation Center',
        'Executive Dining Hall',
        'KU Vice Chancellor Office',
        'KU Basketball Court',
        'Ground',
        'Department of Computer Science and Engineering',
        'KU Law Block',
        '23A',
        'Block No: 08',
        'AKUA',
        'Indoor Games Hall',
        'Nepal Investment Mega Bank',
        'Power System Lab',
        'Department of Pharmacy',
        'Information and Research Processing Research Lab',
        'NTIC',
        'Golo Ghar',
        'Pokhari',
        'KU TTC',
        'Gol Ghar',
        'Block: 09',
        'Saraswati Temple',
        'Staff Quarters',
        'Department of Management',
        'Volleyball Ground',
        'School of Science Project Lab',
        'KU International Hostel',
        'Pelton Chowk',
        'KU Green Hydrogen Lab',
        'ATM',
        'Robotics Club Lab',
        'UMN Science Block',
        'Department of Geomatics Engineering',
        'VC Office',
        'KU Parking',
        'Social hall',
        'KU Gate',
        'Block No: 07',
        'KU Gym',
        'Block: 03',
        'Active Learning Lab',
        'KU Museum',
        'KU Supercomputer',
        'Civil Engineering Lab',
        'Container',
        '25 Lakh Stone',
        'Waste Management',
        'ISMS',
        'Turbine Testing Lab',
        'Department of Law',
        'KU Canteen',
        'Semicircle Park',
        'Swimming Pool',
        'Dabba Stationary',
        'Department of Chemistry',
        'Department of Physics',
        'Exam Controller Office',
        'Cricket Net Practice ',
        'Dean Office SOE',
        'KU Cafe',
        'DOCSE',
        'SoS Account Section',
        'Bus Inquiry Office',
        'IRPRL',
        'Canteen: 02',
        'Mechanical Workshop']

const labels_detail =
    [{ 'label': 'KU Gate', 'id': 1 },
    { 'label': 'ATM', 'id': 1 },
    { 'label': 'Pelton Chowk', 'id': 2 },
    { 'label': 'Pokhari', 'id': 4 },
    { 'label': 'Saraswati Temple', 'id': 4 },
    { 'label': 'Administration Block', 'id': 7 },
    { 'label': 'Main Building', 'id': 7 },
    { 'label': 'KU Vice Chancellor Office', 'id': 7 },
    { 'label': 'VC Office', 'id': 7 },
    { 'label': 'KU Canteen', 'id': 11 },
    { 'label': 'Executive Dining Hall', 'id': 11 },
    { 'label': 'CV Raman Auditorium', 'id': 16 },
    { 'label': 'Library Lawn', 'id': 20 },
    { 'label': 'KU Library', 'id': 22 },
    { 'label': 'Block: 03', 'id': 24 },
    { 'label': 'Container', 'id': 24 },
    { 'label': 'Dabba Stationary', 'id': 24 },
    { 'label': 'ISMS', 'id': 24 },
    { 'label': 'KU Fountain', 'id': 26 },
    { 'label': 'KU Cafe', 'id': 27 },
    { 'label': 'KU Park', 'id': 29 },
    { 'label': '25 Lakh Stone', 'id': 29 },
    { 'label': 'Semicircle Park', 'id': 29 },
    { 'label': 'Girls Hostel', 'id': 30 },
    { 'label': 'KU Bike Parking', 'id': 31 },
    { 'label': 'Nepal Investment Mega Bank', 'id': 32 },
    { 'label': 'Staff Quarters', 'id': 32 },
    { 'label': 'Exam Controller Office', 'id': 32 },
    { 'label': 'Bus Inquiry Office', 'id': 32 },
    { 'label': 'AKUA', 'id': 34 },
    { 'label': 'aqua', 'id': 34 },
    { 'label': 'Department of Environmental Science and Engineering', 'id': 36 },
    { 'label': 'Waste Management', 'id': 36 },
    { 'label': 'WEIR', 'id': 37 },
    { 'label': 'School of Science Project Lab', 'id': 37 },
    { 'label': 'Civil Engineering Lab', 'id': 37 },
    { 'label': 'Gol Ghar', 'id': 39 },
    { 'label': 'Golo Ghar', 'id': 39 },
    { 'label': 'SHEDS', 'id': 39 },
    { 'label': 'Department of Mathematics', 'id': 39 },
    { 'label': 'Department of Chemistry', 'id': 39 },
    { 'label': 'Block: 06', 'id': 41 },
    { 'label': 'UMN Science Block', 'id': 41 },
    { 'label': 'Department of Physics', 'id': 41 },
    { 'label': 'Dean Office SoS', 'id': 41 },
    { 'label': 'SoS Account Section', 'id': 41 },
    { 'label': 'Department of Biotechnology', 'id': 42 },
    { 'label': 'Block No: 07', 'id': 42 },
    { 'label': 'Electronics and Electrical Engineering Block', 'id': 45 },
    { 'label': 'Block No: 08', 'id': 45 },
    { 'label': 'Information and Research Processing Research Lab', 'id': 45 },
    { 'label': 'IRPRL', 'id': 45 },
    { 'label': 'Electronics and Electrical Lab', 'id': 46 },
    { 'label': 'Turbine Testing Lab', 'id': 46 },
    { 'label': 'Power System Lab', 'id': 46 },
    { 'label': 'High Voltage Lab', 'id': 46 },
    { 'label': 'Robotics Club Lab', 'id': 47 },
    { 'label': 'KU Supercomputer', 'id': 47 },
    { 'label': 'Department of Computer Science and Engineering', 'id': 48 },
    { 'label': 'DOCSE', 'id': 48 },
    { 'label': 'Department of Geomatics Engineering', 'id': 48 },
    { 'label': 'Block: 09', 'id': 48 },
    { 'label': 'Dean Office SOE', 'id': 48 },
    { 'label': 'Active Learning Lab', 'id': 48 },
    { 'label': 'KU Corner', 'id': 52 },
    { 'label': 'KU Museum', 'id': 52 },
    { 'label': 'KU Mesh', 'id': 56 },
    { 'label': 'Canteen: 02', 'id': 56 },
    { 'label': 'Engineering Drawing Lab', 'id': 58 },
    { 'label': 'KU International Hostel', 'id': 58 },
    { 'label': 'KU Girls Hostel New', 'id': 58 },
    { 'label': 'Department of Law', 'id': 60 },
    { 'label': 'KU Law Block', 'id': 60 },
    { 'label': 'KU Boys Hostel', 'id': 63 },
    { 'label': 'Social hall', 'id': 63 },
    { 'label': 'Indoor Games Hall', 'id': 63 },
    { 'label': 'KU Gym', 'id': 64 },
    { 'label': 'Cricket Net Practice ', 'id': 67 },
    { 'label': 'NTIC', 'id': 68 },
    { 'label': 'Nepal Technology Innovation Center', 'id': 68 },
    { 'label': 'Mechanical Workshop', 'id': 69 },
    { 'label': 'KU Basketball Court', 'id': 70 },
    { 'label': 'KU Football Ground', 'id': 73 },
    { 'label': 'Ground', 'id': 73 },
    { 'label': 'Volleyball Ground', 'id': 73 },
    { 'label': 'Cricket Pitch', 'id': 73 },
    { 'label': 'Swimming Pool', 'id': 75 },
    { 'label': 'Multipurpose Hall', 'id': 77 },
    { 'label': 'KU Green Hydrogen Lab', 'id': 77 },
    { 'label': '23A', 'id': 79 },
    { 'label': 'KU TTC', 'id': 80 },
    { 'label': 'KU Technical Training Center', 'id': 80 },
    { 'label': 'KU Automobile Lab', 'id': 80 },
    { 'label': 'Block No 10', 'id': 82 },
    { 'label': 'Department of Management', 'id': 82 },
    { 'label': 'Department of Architecture', 'id': 82 },
    { 'label': 'KU Chinese Hall', 'id': 82 },
    { 'label': 'Department of Civil Engineering', 'id': 83 },
    { 'label': 'Department of Pharmacy', 'id': 84 },
    { 'label': 'KU Parking', 'id': 87 }]